import {
  User,
  Person,
  Meeting,
  Commitment,
  FieldSubmission,
  KnowledgeDocument,
  Issue,
  AuditEvent,
  NotificationItem
} from '@/src/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Dr. Wanjiku Mwangi',
    email: 'wanjiku.mwangi@campaign.ops',
    role: 'Campaign Director',
    badge: 'HQ Director',
    assignedRegion: 'National HQ',
    status: 'active',
  },
  {
    id: 'usr-2',
    name: 'David Ochieng',
    email: 'david.ochieng@campaign.ops',
    role: 'Admin',
    badge: 'Lead Systems Architect',
    assignedRegion: 'Central Command',
    status: 'active',
  },
  {
    id: 'usr-3',
    name: 'Fatuma Hassan',
    email: 'fatuma.hassan@campaign.ops',
    role: 'Operations Lead',
    badge: 'Field Ops Central',
    assignedRegion: 'Nairobi & Coast Corridors',
    status: 'active',
  },
  {
    id: 'usr-4',
    name: 'Ezekiel Kiprop',
    email: 'ezekiel.kiprop@campaign.ops',
    role: 'Field Mobilizer',
    badge: 'Rift & Western Cell',
    assignedRegion: 'Nakuru County',
    status: 'active',
  },
  {
    id: 'usr-5',
    name: 'Grace Nyambura',
    email: 'grace.nyambura@campaign.ops',
    role: 'Intelligence Analyst',
    badge: 'Strategic Intel',
    assignedRegion: 'National HQ',
    status: 'active',
  },
];

export const INITIAL_PEOPLE: Person[] = [
  {
    id: 'per-101',
    fullName: 'Elder Josephat Kariuki',
    nationalId: '10984214',
    phone: '+254 722 849 102',
    alternativePhone: '+254 733 910 234',
    email: 'j.kariuki.elder@gmail.com',
    county: 'Kiambu',
    constituency: 'Kiambaa',
    ward: 'Karuri',
    category: 'Community Elder',
    influenceScore: 9,
    status: 'active',
    notes: 'Key community elder and council chairman. Commands high respect among 14 church parish councils and local agricultural cooperatives.',
    tags: ['Elder Council', 'Agri-Coop', 'Church Leader', 'High-Influence'],
    createdAt: '2026-07-14T08:30:00Z',
    updatedAt: '2026-08-28T14:15:00Z',
    metrics: {
      commitmentsCount: 3,
      meetingsCount: 4,
      issuesCount: 1,
      interactionsLast30Days: 6,
    },
  },
  {
    id: 'per-102',
    fullName: 'Hon. Beatrice Atieno',
    nationalId: '21094320',
    phone: '+254 711 405 918',
    email: 'beatrice.atieno.guild@yahoo.com',
    county: 'Nairobi',
    constituency: 'Embakasi Central',
    ward: 'Kayole North',
    category: 'Business Guild Leader',
    influenceScore: 8,
    status: 'active',
    notes: 'Chairperson of the Small Traders & Market Hawkers Alliance. Coordinates over 4,200 micro-retailers along the Spine Road corridor.',
    tags: ['Market Traders', 'Women Leader', 'SME Alliance'],
    createdAt: '2026-07-19T10:00:00Z',
    updatedAt: '2026-08-30T09:45:00Z',
    metrics: {
      commitmentsCount: 4,
      meetingsCount: 5,
      issuesCount: 2,
      interactionsLast30Days: 9,
    },
  },
  {
    id: 'per-103',
    fullName: 'Brian Kiprono Cheruiyot',
    nationalId: '32840912',
    phone: '+254 708 612 884',
    email: 'brian.cheruiyot.youth@proton.me',
    county: 'Nakuru',
    constituency: 'Nakuru Town East',
    ward: 'Biashara',
    category: 'Youth Coordinator',
    influenceScore: 8,
    status: 'active',
    notes: 'Head of Boda Boda operators network and university student union representative. Key driver of voter registration campaigns.',
    tags: ['Youth Wing', 'Boda Boda Alliance', 'Campus League'],
    createdAt: '2026-08-01T11:20:00Z',
    updatedAt: '2026-08-31T16:00:00Z',
    metrics: {
      commitmentsCount: 5,
      meetingsCount: 3,
      issuesCount: 1,
      interactionsLast30Days: 12,
    },
  },
  {
    id: 'per-104',
    fullName: 'Sheikh Omar Salim Bakari',
    nationalId: '18492011',
    phone: '+254 720 339 184',
    county: 'Mombasa',
    constituency: 'Mvita',
    ward: 'Old Town',
    category: 'Religious Leader',
    influenceScore: 9,
    status: 'active',
    notes: 'Interfaith peace council mediator and coastal community elder. Crucial for organizing peaceful civic dialogue forums.',
    tags: ['Interfaith', 'Peace Council', 'Coastal Elder'],
    createdAt: '2026-07-22T09:15:00Z',
    updatedAt: '2026-08-25T11:30:00Z',
    metrics: {
      commitmentsCount: 2,
      meetingsCount: 2,
      issuesCount: 0,
      interactionsLast30Days: 4,
    },
  },
  {
    id: 'per-105',
    fullName: 'Tabitha Ndunge Musyoka',
    nationalId: '24910283',
    phone: '+254 723 901 448',
    email: 'tabitha.musyoka@cbo-machakos.org',
    county: 'Machakos',
    constituency: 'Machakos Town',
    ward: 'Muvuti/Kiima-Kimwe',
    category: 'Grassroots Mobilizer',
    influenceScore: 7,
    status: 'active',
    notes: 'Leads 28 self-help women groups with deep penetration into rural polling divisions.',
    tags: ['Women Table Banking', 'Grassroots', 'Rural Mobilizer'],
    createdAt: '2026-08-05T14:00:00Z',
    updatedAt: '2026-08-29T10:10:00Z',
    metrics: {
      commitmentsCount: 2,
      meetingsCount: 3,
      issuesCount: 1,
      interactionsLast30Days: 7,
    },
  },
  {
    id: 'per-106',
    fullName: 'Pastor Samuel Ondiek',
    nationalId: '15902834',
    phone: '+254 721 884 920',
    county: 'Kisumu',
    constituency: 'Kisumu Central',
    ward: 'Kondele',
    category: 'Religious Leader',
    influenceScore: 8,
    status: 'active',
    notes: 'Pastor and local peace ambassador with wide reach across informal settlements.',
    tags: ['Clergy', 'Peace Ambassador', 'Faith-Based'],
    createdAt: '2026-08-10T12:00:00Z',
    updatedAt: '2026-08-26T17:40:00Z',
    metrics: {
      commitmentsCount: 1,
      meetingsCount: 2,
      issuesCount: 0,
      interactionsLast30Days: 5,
    },
  },
  {
    id: 'per-107',
    fullName: 'Mercy Chebet Langat',
    nationalId: '34819024',
    phone: '+254 701 559 320',
    county: 'Kericho',
    constituency: 'Ainamoi',
    ward: 'Kipchimchim',
    category: 'Key Influencer',
    influenceScore: 7,
    status: 'active',
    notes: 'Smallholder tea farmers association coordinator and digital grassroots influencer.',
    tags: ['Tea Sector', 'Agri-Voice', 'Digital Mobilizer'],
    createdAt: '2026-08-12T15:30:00Z',
    updatedAt: '2026-08-31T08:00:00Z',
    metrics: {
      commitmentsCount: 3,
      meetingsCount: 2,
      issuesCount: 1,
      interactionsLast30Days: 8,
    },
  },
  {
    id: 'per-108',
    fullName: 'John Kamau Karanja',
    nationalId: '19823401',
    phone: '+254 712 345 678',
    county: 'Kiambu',
    constituency: 'Ruiru',
    ward: 'Kahawa Sukari',
    category: 'Business Guild Leader',
    influenceScore: 7,
    status: 'draft',
    duplicateFlag: true,
    duplicateNotes: 'Detected potential duplicate with incoming field submission FS-8842 from Ruiru polling desk.',
    notes: 'Real estate and local hardware merchants association secretary. Has pending digital capture confirmation.',
    tags: ['Merchants Guild', 'Pending-Verification'],
    createdAt: '2026-08-28T09:00:00Z',
    updatedAt: '2026-09-01T11:00:00Z',
    metrics: {
      commitmentsCount: 1,
      meetingsCount: 1,
      issuesCount: 1,
      interactionsLast30Days: 3,
    },
  },
];

export const INITIAL_MEETINGS: Meeting[] = [
  {
    id: 'mtg-201',
    title: 'Kiambu Agricultural Cooperatives Strategic Alignment',
    agenda: 'Harmonize grassroots commitments with 14 coffee & tea cooperative leaders prior to field rally.',
    location: 'Banana Hill Community Hall, Karuri Ward, Kiambu',
    venueType: 'Physical',
    date: '2026-09-02',
    time: '09:00',
    durationMinutes: 90,
    status: 'scheduled',
    leadOrganizer: 'Dr. Wanjiku Mwangi',
    leadOrganizerId: 'usr-1',
    participants: [
      { personId: 'per-101', name: 'Elder Josephat Kariuki', role: 'Chairperson / Key Stakeholder', confirmed: true },
      { personId: 'usr-3', name: 'Fatuma Hassan', role: 'Ops Lead / Note Taker', confirmed: true },
      { personId: 'usr-5', name: 'Grace Nyambura', role: 'Strategic Intelligence Lead', confirmed: true },
    ],
    aiPreparationBrief: {
      summary: 'High-leverage session with Karuri agricultural council. Elder Josephat previously requested guarantees on subsidized fertilizer distribution logistics.',
      keyObjectives: [
        'Secure endorsement for regional voter mobilization drive on Sept 12.',
        'Address overdue commitment COM-301 regarding rural feeder roads review.',
        'Obtain verified list of 120 ward-level polling marshals.',
      ],
      potentialRisks: [
        'Discontent over fertilizer dispatch delays from previous season.',
        'Friction between youth boda-boda leadership and traditional market elders.',
      ],
      suggestedTalkingPoints: [
        'Affirm the decentralized distribution model for agricultural inputs.',
        'Commit to specific timeline for local market drainage upgrade.',
        'Acknowledge Elder Josephat’s 20-year stewardship in Karuri community governance.',
      ],
      historicalContext: 'Josephat Kariuki hosted our initial constituency delegation in July. All 4 previous meetings have yielded high turnout pledges.',
    },
    notes: 'Preparation packets distributed to field coordinators. Briefing deck uploaded to Knowledge repository.',
    decisions: [],
    commitmentsGenerated: ['com-301'],
    issuesGenerated: [],
  },
  {
    id: 'mtg-202',
    title: 'Kayole Market Traders Security & Licensing Dialogue',
    agenda: 'Resolve municipal licensing harassment grievances and formalize micro-trader committee support.',
    location: 'Spine Road Community Pavilion, Embakasi Central, Nairobi',
    venueType: 'Physical',
    date: '2026-09-02',
    time: '14:30',
    durationMinutes: 75,
    status: 'scheduled',
    leadOrganizer: 'Fatuma Hassan',
    leadOrganizerId: 'usr-3',
    participants: [
      { personId: 'per-102', name: 'Hon. Beatrice Atieno', role: 'Hawkers Alliance Chairperson', confirmed: true },
      { personId: 'usr-1', name: 'Dr. Wanjiku Mwangi', role: 'Campaign Director', confirmed: true },
    ],
    aiPreparationBrief: {
      summary: 'Beatrice Atieno commands direct loyalty of 4,200 traders. High energy crowd expected; focus on tangible county fee reduction pacts.',
      keyObjectives: [
        'Formalize MoU with Market Hawkers Alliance.',
        'Deploy 25 mobile field scanners for on-site registration verification.',
      ],
      potentialRisks: [
        'Rival traders splinter group threatening boycotts unless given equal representation.',
      ],
      suggestedTalkingPoints: [
        'Specific 35% reduction pledge on single business permits.',
        'Night-market solar floodlight infrastructure roadmap.',
      ],
      historicalContext: 'Last interaction occurred during the July 28 consultative forum where 180 new volunteer cards were signed.',
    },
    decisions: [],
    commitmentsGenerated: ['com-302'],
    issuesGenerated: ['iss-501'],
  },
  {
    id: 'mtg-203',
    title: 'Rift Valley Youth Mobilizers Weekly Tactical Sync',
    agenda: 'Review digital form digitizations, campus voter registration drives, and boda-boda logistics.',
    location: 'Nakuru Command Hub / Secure Virtual Room 4',
    venueType: 'Secure Virtual',
    date: '2026-09-03',
    time: '11:00',
    durationMinutes: 60,
    status: 'scheduled',
    leadOrganizer: 'Ezekiel Kiprop',
    leadOrganizerId: 'usr-4',
    participants: [
      { personId: 'per-103', name: 'Brian Kiprono Cheruiyot', role: 'Youth League Coordinator', confirmed: true },
      { personId: 'usr-4', name: 'Ezekiel Kiprop', role: 'Field Operations Lead', confirmed: true },
    ],
    aiPreparationBrief: {
      summary: 'Brian Cheruiyot collected 450 paper registration slips over the weekend. 42 slips currently pending OCR duplicate verification.',
      keyObjectives: [
        'Audit field OCR submission quality across 6 Nakuru sub-counties.',
        'Confirm fuel allowance disbursement schedule for 40 boda riders.',
      ],
      potentialRisks: [
        'Logistical delays in delivery of physical campaign merchandise and badges.',
      ],
      suggestedTalkingPoints: [
        'Praise the fast adoption of the mobile camera scanner app.',
        'Clarify strict human-verification gate before records enter central voter database.',
      ],
      historicalContext: 'Nakuru cell registered the fastest week-on-week growth in grassroots delegate sign-ups.',
    },
    decisions: [],
    commitmentsGenerated: ['com-303'],
    issuesGenerated: [],
  },
  {
    id: 'mtg-204',
    title: 'Coastal Peace & Interfaith Delegation Debrief',
    agenda: 'Review security guarantees and community outreach outcomes following Mombasa interfaith townhall.',
    location: 'Mvita Cultural Center, Old Town, Mombasa',
    venueType: 'Physical',
    date: '2026-08-29',
    time: '16:00',
    durationMinutes: 120,
    status: 'completed',
    leadOrganizer: 'Dr. Wanjiku Mwangi',
    leadOrganizerId: 'usr-1',
    participants: [
      { personId: 'per-104', name: 'Sheikh Omar Salim Bakari', role: 'Interfaith Lead', confirmed: true },
      { personId: 'usr-5', name: 'Grace Nyambura', role: 'Strategic Intelligence', confirmed: true },
    ],
    notes: 'Meeting concluded with 100% consensus on non-violent rally guidelines. Signed joint declaration delivered to Secretariat.',
    decisions: [
      'Publish joint interfaith harmony communiqué across 6 coastal FM radio stations.',
      'Deploy joint monitor teams at all major youth sports tournaments in September.',
    ],
    commitmentsGenerated: ['com-304'],
    issuesGenerated: [],
  },
];

export const INITIAL_COMMITMENTS: Commitment[] = [
  {
    id: 'com-301',
    title: 'Deliver Kiambaa Feeder Roads Engineering Assessment',
    description: 'Provide Elder Josephat Kariuki and the parish committee with the technical feasibility brief on the 8km Karuri-Banana road rehabilitation.',
    ownerId: 'usr-3',
    ownerName: 'Fatuma Hassan',
    relatedPersonId: 'per-101',
    relatedPersonName: 'Elder Josephat Kariuki',
    relatedMeetingId: 'mtg-201',
    relatedMeetingTitle: 'Kiambu Agricultural Cooperatives Strategic Alignment',
    dueDate: '2026-09-01',
    priority: 'critical',
    status: 'overdue',
    location: 'Kiambu County',
    auditTrail: [
      {
        id: 'aud-1',
        timestamp: '2026-08-20T10:00:00Z',
        action: 'Created from Meeting mtg-201 preparation',
        performedBy: 'Dr. Wanjiku Mwangi',
      },
      {
        id: 'aud-2',
        timestamp: '2026-09-01T18:00:00Z',
        action: 'Flagged Overdue by System Monitoring',
        performedBy: 'System Engine',
        details: 'Grace period expired without completion proof note.',
      },
    ],
  },
  {
    id: 'com-302',
    title: 'Disburse Fuel Vouchers to Embakasi Central Hawkers Fleet',
    description: 'Issue approved electronic fuel allocations to 30 volunteer motorcade riders ahead of tomorrow’s market caravan.',
    ownerId: 'usr-3',
    ownerName: 'Fatuma Hassan',
    relatedPersonId: 'per-102',
    relatedPersonName: 'Hon. Beatrice Atieno',
    relatedMeetingId: 'mtg-202',
    relatedMeetingTitle: 'Kayole Market Traders Security & Licensing Dialogue',
    dueDate: '2026-09-02',
    priority: 'high',
    status: 'pending',
    location: 'Nairobi County',
    auditTrail: [
      {
        id: 'aud-3',
        timestamp: '2026-08-30T14:20:00Z',
        action: 'Created by Operations Lead',
        performedBy: 'Fatuma Hassan',
      },
    ],
  },
  {
    id: 'com-303',
    title: 'Verify 42 Paper Submissions from Biashara Ward Drive',
    description: 'Complete human audit and duplicate resolution on batch FS-8842 scanned by Nakuru field mobilizers.',
    ownerId: 'usr-5',
    ownerName: 'Grace Nyambura',
    relatedPersonId: 'per-103',
    relatedPersonName: 'Brian Kiprono Cheruiyot',
    relatedMeetingId: 'mtg-203',
    relatedMeetingTitle: 'Rift Valley Youth Mobilizers Weekly Sync',
    dueDate: '2026-09-02',
    priority: 'high',
    status: 'pending',
    location: 'Nakuru County',
    auditTrail: [
      {
        id: 'aud-4',
        timestamp: '2026-08-31T17:15:00Z',
        action: 'Assigned to Strategic Intelligence Lead',
        performedBy: 'Dr. Wanjiku Mwangi',
      },
    ],
  },
  {
    id: 'com-304',
    title: 'Broadcast Interfaith Communiqué on Baraka FM & Radio Rahma',
    description: 'Confirm broadcast slot times and furnish audio clips to coastal media houses for peace declaration.',
    ownerId: 'usr-1',
    ownerName: 'Dr. Wanjiku Mwangi',
    relatedPersonId: 'per-104',
    relatedPersonName: 'Sheikh Omar Salim Bakari',
    relatedMeetingId: 'mtg-204',
    relatedMeetingTitle: 'Coastal Peace & Interfaith Delegation Debrief',
    dueDate: '2026-08-31',
    priority: 'medium',
    status: 'completed',
    completedAt: '2026-08-31T11:45:00Z',
    completedBy: 'Dr. Wanjiku Mwangi',
    completionProofNote: 'Confirmed 12 total spots aired across both stations. Audio recordings archived in Knowledge repository.',
    location: 'Mombasa County',
    auditTrail: [
      {
        id: 'aud-5',
        timestamp: '2026-08-29T17:30:00Z',
        action: 'Created from Meeting mtg-204 decisions',
        performedBy: 'Dr. Wanjiku Mwangi',
      },
      {
        id: 'aud-6',
        timestamp: '2026-08-31T11:45:00Z',
        action: 'Marked as Completed with Verification Proof',
        performedBy: 'Dr. Wanjiku Mwangi',
      },
    ],
  },
  {
    id: 'com-305',
    title: 'Deliver 150 Branded Table-Banking Ledgers to Machakos CBOs',
    description: 'Dispatch physical record books and coordinator badges to Tabitha Musyoka for women self-help network.',
    ownerId: 'usr-4',
    ownerName: 'Ezekiel Kiprop',
    relatedPersonId: 'per-105',
    relatedPersonName: 'Tabitha Ndunge Musyoka',
    dueDate: '2026-09-04',
    priority: 'medium',
    status: 'pending',
    location: 'Machakos County',
    auditTrail: [
      {
        id: 'aud-7',
        timestamp: '2026-08-28T08:10:00Z',
        action: 'Created by Field Mobilizer',
        performedBy: 'Ezekiel Kiprop',
      },
    ],
  },
  {
    id: 'com-306',
    title: 'Audit Polling Agent Roster for Kondele Division',
    description: 'Validate accreditation credentials for 48 volunteer polling agents against official electoral register guidelines.',
    ownerId: 'usr-5',
    ownerName: 'Grace Nyambura',
    relatedPersonId: 'per-106',
    relatedPersonName: 'Pastor Samuel Ondiek',
    dueDate: '2026-08-30',
    priority: 'critical',
    status: 'overdue',
    location: 'Kisumu County',
    auditTrail: [
      {
        id: 'aud-8',
        timestamp: '2026-08-22T09:00:00Z',
        action: 'Created by Intelligence Analyst',
        performedBy: 'Grace Nyambura',
      },
      {
        id: 'aud-9',
        timestamp: '2026-08-30T23:59:00Z',
        action: 'Flagged Overdue by System Engine',
        performedBy: 'System Engine',
      },
    ],
  },
];

export const INITIAL_SUBMISSIONS: FieldSubmission[] = [
  {
    id: 'fs-8842',
    batchNumber: 'BATCH-NBI-2026-088',
    formType: 'Voter Mobilization & Pledges',
    capturedAt: '2026-09-01T15:42:00Z',
    capturedBy: 'Ezekiel Kiprop',
    capturedById: 'usr-4',
    location: {
      county: 'Kiambu',
      constituency: 'Ruiru',
      ward: 'Kahawa Sukari',
      pollingStation: '048 - Kahawa Sukari Primary School',
    },
    status: 'pending_review',
    originalImageUrl: 'https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&w=1200&q=80',
    extractedFields: [
      {
        id: 'fld-1',
        name: 'fullName',
        label: 'Full Name (Voter / Delegate)',
        value: 'John Kamau Karanja',
        confidence: 0.98,
        originalValue: 'John Kamau Karanja',
        boundingBox: { x: 18, y: 24, width: 62, height: 6 },
      },
      {
        id: 'fld-2',
        name: 'phone',
        label: 'Primary Phone Number',
        value: '+254 712 345 678',
        confidence: 0.94,
        originalValue: '0712 345 678',
        boundingBox: { x: 18, y: 32, width: 44, height: 6 },
      },
      {
        id: 'fld-3',
        name: 'nationalId',
        label: 'National Identity Number',
        value: '19823401',
        confidence: 0.89,
        originalValue: '19823401',
        boundingBox: { x: 18, y: 40, width: 38, height: 6 },
      },
      {
        id: 'fld-4',
        name: 'county',
        label: 'Registered County',
        value: 'Kiambu',
        confidence: 0.96,
        originalValue: 'Kiambu',
        boundingBox: { x: 18, y: 48, width: 30, height: 6 },
      },
      {
        id: 'fld-5',
        name: 'constituency',
        label: 'Constituency',
        value: 'Ruiru',
        confidence: 0.91,
        originalValue: 'Ruiru',
        boundingBox: { x: 50, y: 48, width: 30, height: 6 },
      },
      {
        id: 'fld-6',
        name: 'ward',
        label: 'Electoral Ward',
        value: 'Kahawa Sukari',
        confidence: 0.76,
        originalValue: 'Kahawa Sukari',
        validationWarning: 'Confidence score 76% (handwriting ink smudge on second word). Verified against constituency ward registry.',
        boundingBox: { x: 18, y: 56, width: 36, height: 6 },
      },
      {
        id: 'fld-7',
        name: 'pledgeCommitment',
        label: 'Pledge Commitment',
        value: 'Agreed to coordinate 25 retail merchants for volunteer caravan',
        confidence: 0.88,
        originalValue: 'Agreed to coordinate 25 retail merchants for volunteer caravan',
        boundingBox: { x: 18, y: 64, width: 72, height: 10 },
      },
    ],
    possibleDuplicate: {
      isDuplicate: true,
      matchedPersonId: 'per-108',
      matchedPersonName: 'John Kamau Karanja (per-108)',
      similarityScore: 0.96,
      reason: 'Exact match on National ID (19823401) and Phone (+254 712 345 678) in Kiambu / Ruiru records.',
    },
    notes: 'Captured via tablet camera at Karuri agricultural trading center.',
  },
  {
    id: 'fs-8843',
    batchNumber: 'BATCH-NKU-2026-041',
    formType: 'Event Sign-up',
    capturedAt: '2026-09-01T14:10:00Z',
    capturedBy: 'Brian Kiprono Cheruiyot',
    capturedById: 'usr-4',
    location: {
      county: 'Nakuru',
      constituency: 'Nakuru Town East',
      ward: 'Biashara',
      pollingStation: '012 - Afraha Stadium Main Gate',
    },
    status: 'pending_review',
    originalImageUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=1200&q=80',
    extractedFields: [
      {
        id: 'fld-10',
        name: 'fullName',
        label: 'Full Name',
        value: 'Agnes Chepkorir Sang',
        confidence: 0.99,
        originalValue: 'Agnes Chepkorir Sang',
        boundingBox: { x: 20, y: 22, width: 55, height: 6 },
      },
      {
        id: 'fld-11',
        name: 'phone',
        label: 'Phone Number',
        value: '+254 714 883 209',
        confidence: 0.97,
        originalValue: '0714 883 209',
        boundingBox: { x: 20, y: 30, width: 40, height: 6 },
      },
      {
        id: 'fld-12',
        name: 'category',
        label: 'Volunteer Category',
        value: 'Campus Youth Mobilizer',
        confidence: 0.85,
        originalValue: 'Campus Youth Mobilizer',
        boundingBox: { x: 20, y: 38, width: 45, height: 6 },
      },
    ],
    possibleDuplicate: {
      isDuplicate: false,
    },
    notes: 'Clean scan with high contrast lighting.',
  },
  {
    id: 'fs-8840',
    batchNumber: 'BATCH-NBI-2026-087',
    formType: 'Community Grievance Log',
    capturedAt: '2026-08-31T17:20:00Z',
    capturedBy: 'Fatuma Hassan',
    capturedById: 'usr-3',
    location: {
      county: 'Nairobi',
      constituency: 'Embakasi Central',
      ward: 'Kayole North',
    },
    status: 'approved',
    originalImageUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=1200&q=80',
    extractedFields: [
      {
        id: 'fld-20',
        name: 'fullName',
        label: 'Complainant / Organizer',
        value: 'Hon. Beatrice Atieno',
        confidence: 0.99,
        originalValue: 'Beatrice Atieno',
      },
      {
        id: 'fld-21',
        name: 'issueSummary',
        label: 'Grievance Description',
        value: 'County municipal enforcement impounded 14 merchant vegetable stalls at Spine Road market.',
        confidence: 0.94,
        originalValue: 'County municipal enforcement impounded 14 merchant vegetable stalls at Spine Road market.',
      },
    ],
    verifiedBy: 'Dr. Wanjiku Mwangi',
    verifiedAt: '2026-08-31T18:30:00Z',
    notes: 'Approved and automatically converted to operational issue ISS-501.',
  },
  {
    id: 'fs-8839',
    batchNumber: 'BATCH-MSB-2026-019',
    formType: 'Delegate Registry',
    capturedAt: '2026-08-29T10:05:00Z',
    capturedBy: 'Sheikh Omar Salim Bakari',
    capturedById: 'usr-1',
    location: {
      county: 'Mombasa',
      constituency: 'Mvita',
      ward: 'Old Town',
    },
    status: 'approved',
    originalImageUrl: 'https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&w=1200&q=80',
    extractedFields: [
      {
        id: 'fld-30',
        name: 'fullName',
        label: 'Delegate Name',
        value: 'Farouk Rashid Mbarak',
        confidence: 0.96,
        originalValue: 'Farouk Rashid Mbarak',
      },
      {
        id: 'fld-31',
        name: 'phone',
        label: 'Phone Number',
        value: '+254 722 710 442',
        confidence: 0.95,
        originalValue: '+254 722 710 442',
      },
    ],
    verifiedBy: 'Grace Nyambura',
    verifiedAt: '2026-08-29T12:00:00Z',
  },
];

export const INITIAL_DOCUMENTS: KnowledgeDocument[] = [
  {
    id: 'doc-401',
    title: 'Kiambu & Murang’a Agricultural Corridor Strategic Assessment',
    type: 'Strategy Memo',
    category: 'Regional Strategy',
    date: '2026-08-28',
    fileSize: '3.4 MB',
    status: 'indexed',
    author: 'Grace Nyambura (Strategic Intel)',
    classification: 'Confidential',
    aiSummary: 'Comprehensive analytical brief on voter consolidation across 12 agricultural constituencies. Outlines specific policy levers: guaranteed coffee cherry advance payments, subsidized fertilizer logistics, and road upgrading promises. Identifies 14 key elders including Elder Josephat Kariuki.',
    keyTakeaways: [
      'Karuri and Banana Hill wards present highest volunteer pledge density in Kiambaa.',
      'Coffee farmers demand formal escrow audit guarantees for cooperative debt relief.',
      'Youth voter apathy in semi-urban fringe can be mitigated through sports tournament sponsorships.',
      'Recommend scheduling high-profile rally in Karuri town center before September 15.',
    ],
    tags: ['Strategy', 'Kiambu', 'Agriculture', 'Elders', 'Voter Turnout'],
    relatedPeopleIds: ['per-101', 'per-108'],
    relatedMeetingIds: ['mtg-201'],
    content: `EXECUTIVE SUMMARY: STRATEGIC CORRIDOR ANALYSIS (KIAMBU-MURANG'A)
1. REGIONAL DEMOGRAPHICS & ELECTORAL WEIGHT
Kiambu County represents 1.3M registered voters across 12 constituencies. The agrarian belt (Kiambaa, Githunguri, Gatundu South, Lari) demonstrates strong voting discipline anchored in tea/coffee cooperative networks.

2. STAKEHOLDER MATRIX
Elder Josephat Kariuki remains the central convener of the Karuri Parish Council. His endorsement reliably swings community opinion across 18 polling streams.

3. STRATEGIC RECOMMENDATIONS
- Operationalize mobile verification units to digitize paper voter sign-ups within 12 hours of field gatherings.
- Fulfill outstanding infrastructure pledges regarding drainage and feeder access.`,
  },
  {
    id: 'doc-402',
    title: 'SME Traders & Informal Economy Policy Platform (Nairobi)',
    type: 'Strategy Memo',
    category: 'Economic Policy',
    date: '2026-08-25',
    fileSize: '2.1 MB',
    status: 'indexed',
    author: 'Fatuma Hassan (Ops Lead)',
    classification: 'Internal Ops',
    aiSummary: 'Operational playbook for engaging Nairobi’s 350,000 informal traders across Kayole, Gikomba, Muthurwa, and Toi markets. Includes legal analysis of county bylaws and proposed licensing fee reduction formulas.',
    keyTakeaways: [
      'Single business permit fees represent 28% of average micro-merchant operating margin.',
      'Alliance with Hon. Beatrice Atieno unlocks organized access to 4,200 active market stall owners.',
      'Night-time solar security lighting is the #1 requested infrastructure intervention.',
    ],
    tags: ['Nairobi', 'Hawkers', 'SME Policy', 'Market Economics'],
    relatedPeopleIds: ['per-102'],
    relatedMeetingIds: ['mtg-202'],
    content: `OPERATIONAL PLAYBOOK: NAIROBI INFORMAL TRADERS GUILD
Formal trade associations in Eastlands operate on high-trust peer accountability. Engaging leadership like Beatrice Atieno must be paired with rapid resolution of municipal licensing confiscation disputes.`,
  },
  {
    id: 'doc-403',
    title: 'Rift Valley Field Operations & Mobile Capture Weekly Audit',
    type: 'Field Report',
    category: 'Field Operations',
    date: '2026-08-30',
    fileSize: '4.8 MB',
    status: 'indexed',
    author: 'Ezekiel Kiprop (Field Mobilizer Lead)',
    classification: 'Field Dissemination',
    aiSummary: 'Weekly metrics report summarizing 1,240 physical sign-up sheets digitized via the camera OCR scanner across Nakuru, Kericho, and Baringo counties. Highlights 96.4% OCR accuracy and 3.6% manual review rate.',
    keyTakeaways: [
      'Camera-first scanning reduced turnaround from 4 days to 45 minutes.',
      'Low lighting conditions at dusk accounted for 80% of duplicate review flags.',
      'Recommends equipping mobilizers with portable LED clip lights for evening registration drives.',
    ],
    tags: ['Field Audit', 'OCR Metrics', 'Nakuru', 'Data Quality'],
    relatedPeopleIds: ['per-103', 'per-107'],
    relatedMeetingIds: ['mtg-203'],
    content: `FIELD AUDIT & TELEMETRY REPORT
Mobile scanners processed 1,240 sheets across 32 polling zones. Dual-pass AI verification correctly flagged 42 potential duplicate identity entries.`,
  },
  {
    id: 'doc-404',
    title: 'Coastal Peace Accord & Interfaith Code of Conduct',
    type: 'Legal/Compliance',
    category: 'Legal & Peace',
    date: '2026-08-29',
    fileSize: '1.7 MB',
    status: 'indexed',
    author: 'Secretariat Legal Counsel',
    classification: 'Internal Ops',
    aiSummary: 'Legal framework and binding code of conduct agreed between campaign leadership, the Council of Imams and Preachers of Kenya (CIPK), and the Coast Interfaith Council of Clergy.',
    keyTakeaways: [
      'Establishes zero-tolerance standard for sectarian or divisive campaign messaging.',
      'Creates a 24/7 hotline for rapid escalation of localized community tensions.',
      'Provides standard clearance protocol for all campaign public address audio scripts.',
    ],
    tags: ['Legal', 'Peace Accord', 'Mombasa', 'Interfaith'],
    relatedPeopleIds: ['per-104'],
    relatedMeetingIds: ['mtg-204'],
    content: `COASTAL INTERFAITH CODE OF CONDUCT
Signed by Dr. Wanjiku Mwangi and Sheikh Omar Salim Bakari. All field events must incorporate the peace pledge prior to candidate address.`,
  },
];

export const INITIAL_ISSUES: Issue[] = [
  {
    id: 'iss-501',
    title: 'County Enforcement Confiscation of Kayole Market Stalls',
    description: 'Municipal county officers impounded 14 vegetable and dry-goods stalls operated by allied Hawkers Alliance members along Spine Road, sparking localized unrest.',
    category: 'Field Friction',
    priority: 'critical',
    status: 'escalated',
    location: 'Embakasi Central, Nairobi',
    reportedBy: 'Hon. Beatrice Atieno',
    reportedById: 'per-102',
    assignedTo: 'Fatuma Hassan',
    assignedToId: 'usr-3',
    createdAt: '2026-08-31T16:20:00Z',
    updatedAt: '2026-09-01T10:15:00Z',
    timeline: [
      {
        id: 'tle-1',
        timestamp: '2026-08-31T16:20:00Z',
        author: 'Hon. Beatrice Atieno',
        content: 'Reported confiscation of 14 stalls by sub-county enforcement officers during evening setup.',
        statusChange: 'open',
      },
      {
        id: 'tle-2',
        timestamp: '2026-08-31T18:00:00Z',
        author: 'Fatuma Hassan',
        content: 'Contacted Sub-County Deputy Administrator. Confirmed goods held at Embakasi yard pending impound fee payment.',
        statusChange: 'investigating',
      },
      {
        id: 'tle-3',
        timestamp: '2026-09-01T09:30:00Z',
        author: 'Dr. Wanjiku Mwangi',
        content: 'Escalated directly to County Operations Desk. Legal counsel dispatched to facilitate administrative release without confrontation.',
        statusChange: 'escalated',
      },
    ],
    relatedPeopleIds: ['per-102'],
    relatedMeetingIds: ['mtg-202'],
    relatedCommitmentIds: ['com-302'],
  },
  {
    id: 'iss-502',
    title: 'Sound Equipment Truck Breakdown on Nakuru-Salgaa Highway',
    description: 'Main audio amplification rig vehicle experienced transmission failure en route to the Rongai youth sports festival.',
    category: 'Logistics & Transport',
    priority: 'high',
    status: 'investigating',
    location: 'Rongai, Nakuru County',
    reportedBy: 'Brian Kiprono Cheruiyot',
    reportedById: 'per-103',
    assignedTo: 'Ezekiel Kiprop',
    assignedToId: 'usr-4',
    createdAt: '2026-09-01T12:00:00Z',
    updatedAt: '2026-09-01T14:40:00Z',
    timeline: [
      {
        id: 'tle-4',
        timestamp: '2026-09-01T12:00:00Z',
        author: 'Brian Kiprono Cheruiyot',
        content: 'Truck stalled at Salgaa trading center. Mobile mechanic dispatched.',
        statusChange: 'open',
      },
      {
        id: 'tle-5',
        timestamp: '2026-09-01T14:40:00Z',
        author: 'Ezekiel Kiprop',
        content: 'Backup sound system rented from Nakuru town center to ensure event proceeds on schedule.',
        statusChange: 'investigating',
      },
    ],
    relatedPeopleIds: ['per-103'],
    relatedMeetingIds: ['mtg-203'],
    relatedCommitmentIds: [],
  },
  {
    id: 'iss-503',
    title: 'Shortage of Physical Paper Mobilization Forms in Karuri',
    description: 'Field mobilizers ran out of physical pledge sheets during the morning church council delegation.',
    category: 'Material Shortage',
    priority: 'medium',
    status: 'resolved',
    location: 'Kiambaa, Kiambu County',
    reportedBy: 'Elder Josephat Kariuki',
    reportedById: 'per-101',
    assignedTo: 'Fatuma Hassan',
    assignedToId: 'usr-3',
    createdAt: '2026-08-30T10:00:00Z',
    updatedAt: '2026-08-30T15:30:00Z',
    timeline: [
      {
        id: 'tle-6',
        timestamp: '2026-08-30T10:00:00Z',
        author: 'Elder Josephat Kariuki',
        content: 'Notified team that 200 additional forms were needed immediately.',
        statusChange: 'open',
      },
      {
        id: 'tle-7',
        timestamp: '2026-08-30T15:30:00Z',
        author: 'Fatuma Hassan',
        content: 'Dispatched 500 printed forms via rider and onboarded 4 mobilizers to the instant digital mobile capture app.',
        statusChange: 'resolved',
      },
    ],
    relatedPeopleIds: ['per-101'],
    relatedMeetingIds: ['mtg-201'],
    relatedCommitmentIds: ['com-301'],
  },
];

export const INITIAL_AUDIT_LOGS: AuditEvent[] = [
  {
    id: 'aud-log-1',
    timestamp: '2026-09-01T19:40:12Z',
    actorId: 'usr-1',
    actorName: 'Dr. Wanjiku Mwangi',
    actorRole: 'Campaign Director',
    action: 'Escalated Issue Status to Escalated',
    domain: 'Issues',
    targetId: 'iss-501',
    targetName: 'County Enforcement Confiscation of Kayole Market Stalls',
    details: 'Dispatched legal counsel and escalated priority to Critical.',
    ipAddress: '102.219.208.14',
  },
  {
    id: 'aud-log-2',
    timestamp: '2026-09-01T18:15:33Z',
    actorId: 'usr-5',
    actorName: 'Grace Nyambura',
    actorRole: 'Intelligence Analyst',
    action: 'Verified AI OCR Submission',
    domain: 'Field',
    targetId: 'fs-8840',
    targetName: 'Community Grievance Log (Kayole North)',
    details: 'Validated extracted fields with 96.5% confidence and converted into operational issue.',
    ipAddress: '102.219.208.18',
  },
  {
    id: 'aud-log-3',
    timestamp: '2026-09-01T16:02:40Z',
    actorId: 'usr-4',
    actorName: 'Ezekiel Kiprop',
    actorRole: 'Field Mobilizer',
    action: 'Uploaded Mobile OCR Batch',
    domain: 'Field',
    targetId: 'fs-8842',
    targetName: 'Batch BATCH-NBI-2026-088 (Kahawa Sukari)',
    details: 'Camera capture uploaded 7 field pledge slips.',
    ipAddress: '41.89.24.110',
  },
  {
    id: 'aud-log-4',
    timestamp: '2026-09-01T14:22:05Z',
    actorId: 'usr-2',
    actorName: 'David Ochieng',
    actorRole: 'Admin',
    action: 'Updated Role Permission Matrix',
    domain: 'Security',
    targetId: 'role-field-mobilizer',
    targetName: 'Field Mobilizer Role Permissions',
    details: 'Added field:capture permission; retained verification restriction to Intelligence/Admin roles.',
    ipAddress: '197.237.158.42',
  },
  {
    id: 'aud-log-5',
    timestamp: '2026-08-31T11:45:00Z',
    actorId: 'usr-1',
    actorName: 'Dr. Wanjiku Mwangi',
    actorRole: 'Campaign Director',
    action: 'Completed Commitment with Proof',
    domain: 'Commitments',
    targetId: 'com-304',
    targetName: 'Broadcast Interfaith Communiqué on Baraka FM',
    details: 'Attached broadcast confirmation invoice and spot logs.',
    ipAddress: '102.219.208.14',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Critical Issue Escalated',
    message: 'Kayole market stall impoundment escalated by Campaign Director.',
    timestamp: '15m ago',
    type: 'urgent',
    read: false,
    linkUrl: '/issues/iss-501',
  },
  {
    id: 'notif-2',
    title: '3 Submissions Awaiting Human Verification',
    message: 'Batch BATCH-NBI-2026-088 contains 1 possible duplicate requiring approval.',
    timestamp: '42m ago',
    type: 'warning',
    read: false,
    linkUrl: '/field/submissions/fs-8842',
  },
  {
    id: 'notif-3',
    title: 'Meeting in 45 Minutes',
    message: 'Kiambu Agricultural Cooperatives Strategic Alignment with Elder Josephat Kariuki.',
    timestamp: '1h ago',
    type: 'info',
    read: false,
    linkUrl: '/meetings/mtg-201',
  },
  {
    id: 'notif-4',
    title: 'Overdue Commitment Alert',
    message: 'Kiambaa Feeder Roads Engineering Assessment passed deadline.',
    timestamp: '2h ago',
    type: 'urgent',
    read: true,
    linkUrl: '/commitments',
  },
];
